name: Java CI with Maven
 
env:
  NAME: 'My Action'
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    env:
        JAVA_VERSION: '11'
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Print name
      run: echo "Hello $NAME. $BUILD. Using Java Version $JAVA_VERSION"
      env:
        BUILD: 'We are currently running the Build job'
